---
name: "Hikka"
guid: "96246472-1c95-4354-96b9-2398e8b03284"
version: "1.0.0.1"
targetAbi: "10.10.6.0"
framework: "net8.0"
overview: "Ukrainian metadata and image provider for anime, manga and novels."
description: >
  Ukrainian metadata and image provider for anime, manga and novels.

category: "Metadata"
owner: "Hot Masya"
artifacts:
  - "Jellyfin.Plugin.Hikka.dll"
changelog: >
  - Added metadata providers for anime series, movies, manga and novels;
  - Added image providers for anime series, movies, manga and novels;
  - Added metadata and image providers for staff and actors.
